sudo: required
dist: trusty

language: go
go: 
  - 1.9.x

before_install:

script: go build -o helloworld

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: helloworld
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
