sudo: required
dist: trusty

language: go
go: 
  - 1.9.x

before_install:
  - echo deb http://ceph.com/debian-{ceph-stable-release}/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
  - wget -q -O- 'https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc' | sudo apt-key add -
  - deb http://ceph.com/debian-emperor raring main
  - sudo apt-get update
  - sudo apt-get install ceph-deploy

script: go build -o helloworld

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: helloworld
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
